/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1p2_ricardoquiroz;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author rjqer
 */
public class FrameJuego extends javax.swing.JFrame {

    /**
     * Creates new form FrameJuego
     */
    public FrameJuego() {
        initComponents();
        armas.add(new Arma("Flatline", 25, 75));
        armas.add(new Arma("Peacekeeper", 70, 40));
        armas.add(new Arma("R301", 18, 90));
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)CB_arma.getModel();
        for (Arma arma : armas) {
            modelo.addElement(arma);
        }
        Arma nuevaarma = (Arma)CB_arma.getSelectedItem();
        personajes.add(new Fortaleza("Newcastle", armas.get(0), 100, 80));
        personajes.add(new Medico("Lifeline", armas.get(1), 100, 10));
        personajes.add(new Rastreador("Pathfinder", armas.get(2), 70, 60));
        DefaultComboBoxModel mod = (DefaultComboBoxModel)CB_seleccionar.getModel();
        for (Personaje personaje : personajes) {
            mod.addElement(personaje);
        }
        Personaje nuevopersonaje = (Personaje)CB_seleccionar.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        Panel_seleccionar = new javax.swing.JPanel();
        Label_selperso = new javax.swing.JLabel();
        CB_seleccionar = new javax.swing.JComboBox<>();
        Button_seleccionar = new javax.swing.JButton();
        Panel_juego = new javax.swing.JPanel();
        Button_comenzar = new javax.swing.JButton();
        Label_restantes = new javax.swing.JLabel();
        TF_atacar = new javax.swing.JTextField();
        Button_atacar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_juego = new javax.swing.JTextArea();
        Panel_crear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FTF_vida = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        CB_tipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        FTF_escudo = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        CB_arma = new javax.swing.JComboBox<>();
        Button_crearperso = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TF_crearnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FTF_precision = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        FTF_dano = new javax.swing.JFormattedTextField();
        Button_creararma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_selperso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_selperso.setText("Seleccionar Personaje");

        Button_seleccionar.setText("Seleccionar");

        javax.swing.GroupLayout Panel_seleccionarLayout = new javax.swing.GroupLayout(Panel_seleccionar);
        Panel_seleccionar.setLayout(Panel_seleccionarLayout);
        Panel_seleccionarLayout.setHorizontalGroup(
            Panel_seleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_seleccionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_seleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Button_seleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(CB_seleccionar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_selperso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        Panel_seleccionarLayout.setVerticalGroup(
            Panel_seleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_seleccionarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Label_selperso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CB_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_seleccionar)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Seleccionar", Panel_seleccionar);

        Button_comenzar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_comenzar.setText("Comenzar");

        Label_restantes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_restantes.setText("Restantes: ");

        Button_atacar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Button_atacar.setText("Atacar");

        TA_juego.setColumns(20);
        TA_juego.setRows(5);
        jScrollPane1.setViewportView(TA_juego);

        javax.swing.GroupLayout Panel_juegoLayout = new javax.swing.GroupLayout(Panel_juego);
        Panel_juego.setLayout(Panel_juegoLayout);
        Panel_juegoLayout.setHorizontalGroup(
            Panel_juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_juegoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Panel_juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_juegoLayout.createSequentialGroup()
                        .addComponent(TF_atacar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Button_atacar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_juegoLayout.createSequentialGroup()
                        .addComponent(Button_comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(Label_restantes)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        Panel_juegoLayout.setVerticalGroup(
            Panel_juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_juegoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_restantes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_atacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_atacar))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Jugar", Panel_juego);

        jLabel1.setText("Nombre");

        jLabel2.setText("Vida");

        FTF_vida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel3.setText("Tipo");

        CB_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fortaleza", "Medico", "Rastreador" }));

        jLabel4.setText("Escudo");

        FTF_escudo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel5.setText("Arma");

        Button_crearperso.setText("Crear Personaje");
        Button_crearperso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_crearpersoMouseClicked(evt);
            }
        });

        jLabel6.setText("Crear Arma");

        jLabel7.setText("Nombre");

        jLabel8.setText("Precision");

        FTF_precision.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel9.setText("Dano");

        Button_creararma.setText("Crear Arma");
        Button_creararma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_creararmaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_crearLayout = new javax.swing.GroupLayout(Panel_crear);
        Panel_crear.setLayout(Panel_crearLayout);
        Panel_crearLayout.setHorizontalGroup(
            Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_crearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_crearLayout.createSequentialGroup()
                        .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_crearLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(155, 155, 155)
                                .addComponent(jLabel5))
                            .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(FTF_precision, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_crearLayout.createSequentialGroup()
                                    .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FTF_escudo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(Panel_crearLayout.createSequentialGroup()
                                            .addGap(84, 84, 84)
                                            .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(FTF_vida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(Panel_crearLayout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel8)
                                                .addComponent(CB_arma, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(30, 30, 30)
                        .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_crearLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(CB_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(Panel_crearLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(Button_crearperso, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(27, Short.MAX_VALUE))))
                    .addGroup(Panel_crearLayout.createSequentialGroup()
                        .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(TF_crearnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addGroup(Panel_crearLayout.createSequentialGroup()
                                .addComponent(FTF_dano, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(Button_creararma, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Panel_crearLayout.setVerticalGroup(
            Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_crearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTF_vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTF_escudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_arma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_crearperso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_crearnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTF_precision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTF_dano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_creararma))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Crear", Panel_crear);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_crearpersoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_crearpersoMouseClicked
        // TODO add your handling code here:
        if (((String)(CB_tipo.getSelectedItem())).equals("Fortaleza")) {
            personajes.add(new Fortaleza(TF_nombre.getText(), ((Arma)CB_arma.getSelectedItem()), (Integer.parseInt(FTF_vida.getText())), Integer.parseInt(FTF_escudo.getText())));
        }
        else if (((String)(CB_tipo.getSelectedItem())).equals("Medico")) {
            personajes.add(new Medico(TF_nombre.getText(), ((Arma)CB_arma.getSelectedItem()), (Integer.parseInt(FTF_vida.getText())), Integer.parseInt(FTF_escudo.getText())));
        }
        else if (((String)(CB_tipo.getSelectedItem())).equals("Rastreador")) {
            personajes.add(new Rastreador(TF_nombre.getText(), ((Arma)CB_arma.getSelectedItem()), (Integer.parseInt(FTF_vida.getText())), Integer.parseInt(FTF_escudo.getText())));
        }        
        DefaultComboBoxModel mod = (DefaultComboBoxModel)CB_seleccionar.getModel();
        //DefaultComboBoxModel.removeAllElements();
        mod.removeAllElements();
        for (Personaje personaje : personajes) {
            mod.addElement(personaje);
        }
        Personaje nuevopersonaje = (Personaje)CB_seleccionar.getSelectedItem();
    }//GEN-LAST:event_Button_crearpersoMouseClicked

    private void Button_creararmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_creararmaMouseClicked
        // TODO add your handling code here:
        armas.add(new Arma(TF_crearnombre.getText(), Integer.parseInt(FTF_dano.getText()), Integer.parseInt(FTF_precision.getText())));
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)CB_arma.getModel();
        modelo.removeAllElements();
        for (Arma arma : armas) {
            modelo.addElement(arma);
        }
        Arma nuevaarma = (Arma)CB_arma.getSelectedItem();
    }//GEN-LAST:event_Button_creararmaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameJuego().setVisible(true);
            }
        });
    }
    
    
    private ArrayList<Arma> armas = new ArrayList();
    private ArrayList<Personaje> personajes = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_atacar;
    private javax.swing.JButton Button_comenzar;
    private javax.swing.JButton Button_creararma;
    private javax.swing.JButton Button_crearperso;
    private javax.swing.JButton Button_seleccionar;
    private javax.swing.JComboBox<String> CB_arma;
    private javax.swing.JComboBox<String> CB_seleccionar;
    private javax.swing.JComboBox<String> CB_tipo;
    private javax.swing.JFormattedTextField FTF_dano;
    private javax.swing.JFormattedTextField FTF_escudo;
    private javax.swing.JFormattedTextField FTF_precision;
    private javax.swing.JFormattedTextField FTF_vida;
    private javax.swing.JLabel Label_restantes;
    private javax.swing.JLabel Label_selperso;
    private javax.swing.JPanel Panel_crear;
    private javax.swing.JPanel Panel_juego;
    private javax.swing.JPanel Panel_seleccionar;
    private javax.swing.JTextArea TA_juego;
    private javax.swing.JTextField TF_atacar;
    private javax.swing.JTextField TF_crearnombre;
    private javax.swing.JTextField TF_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
